import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import Layout from "@/components/layout";
import LeftHomeSection from "@/components/leftHomeSection";
import RightHomeSection from "@/components/rightHomeSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>KalART</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main className={styles.main}>
          <LeftHomeSection />
          <RightHomeSection />
        </main>
      </Layout>
    </>
  );
}
